// Generated by Selenium IDE
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import com.applitools.eyes.selenium.Eyes;
import com.applitools.eyes.RectangleSize;
import com.applitools.eyes.selenium.BrowserType;
import com.applitools.eyes.selenium.Configuration;
import com.applitools.eyes.visualgrid.model.DeviceName;
import com.applitools.eyes.visualgrid.model.ScreenOrientation;
import com.applitools.eyes.visualgrid.services.VisualGridRunner;
import com.applitools.eyes.selenium.fluent.Target;
import com.applitools.eyes.AccessibilityLevel;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
public class UntitledddddddddddddddddddddddddddddTest {
  private RemoteWebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private Eyes eyes;
  private VisualGridRunner runner;
  final int concurrency = 5;
  private String preRenderHook;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://selenium:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    runner = new VisualGridRunner(concurrency);
    eyes = new Eyes(runner);
    Configuration config = eyes.getConfiguration();
    config.setAccessibilityValidation(AccessibilityLevel.AA);
    config.addBrowser(2048, 1536, BrowserType.CHROME);
    config.addDeviceEmulation(DeviceName.iPhone6_7_8_Plus, ScreenOrientation.LANDSCAPE);
    eyes.setConfiguration(config);
    eyes.open(driver, "kkkk", "Untitleddddddddddddddddddddddddddddd");
  }
  @After
  public void tearDown() {
    driver.quit();
    runner.getAllTestResults();
    eyes.abortIfNotClosed();
  }
  @Test
  public void untitleddddddddddddddddddddddddddddd() {
    driver.get("https://www.google.com/");
    Eyes.setViewportSize(driver, new RectangleSize(1440, 998));
    preRenderHook = "console.log(\"blah\");";
    eyes.check(Target.window().fully().beforeRenderScreenshotHook(preRenderHook));
    eyes.check(Target.window().region(By.name("q")).beforeRenderScreenshotHook(preRenderHook));
  }
}
